In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/Jeepofun/Final-Project/main/Data/Raw%20data4.csv', header=1)
df = df.drop(columns=['Unnamed: 0'])
df = df.replace(r'^\s*$', np.nan, regex=True)
df = df.rename(columns={'Base_ Engine': 'Base_Engine'})
df.head()

,Name,Base_price,Body_style,Seats,Base_Engine,Base_Power,Mileage,Drive,Towing,Min_cargo_L,Front_headroom,Front_legroom,Rear_legroom,Rear_shoulder,Fuel_capacity,Batt,Range
0,2021 Acura RDX,44505,SUV,5,Gasoline,272.0,9.9,AWD,1500.0,835.0,39.6,41.6,38.4,56.6,65.0,0.0,654.0
1,2022 Acura MDX,56405,SUV,7,Gasoline,290.0,11.2,AWD,5000.0,513.0,38.5,41.6,38.5,60.3,70.0,0.0,625.0
2,2021 Acura ILX,30805,Sedan,5,Gasoline,201.0,8.6,FWD,0.0,350.0,38,42.3,34,53.5,50.0,0.0,581.0
3,2022 Acura NSX,221500,Coupe,2,Hybrid,600.0,11.0,AWD,0.0,110.0,38.3,42.9,0,0,59.0,1.3,539.0
4,2021 Acura TLX,44105,Sedan,5,Gasoline,272.0,9.8,AWD,0.0,382.0,37.2,42.5,34.9,55,60.0,0.0,612.0

In [5]:
df['Front_headroom']=df['Front_headroom'].astype('float64')
df['Front_legroom']=df['Front_legroom'].astype('float64')
df['Rear_legroom']=df['Rear_legroom'].astype('float64')
df['Rear_shoulder']=df['Rear_shoulder'].astype('float64')

In [6]:
df['Range'] = df['Range'].fillna(df['Range'].mean())
df['Batt'] = df['Batt'].fillna(df['Batt'].mean())
df['Mileage']=df['Mileage'].fillna(df['Mileage'].mean())
df['Min_cargo_L']=df['Min_cargo_L'].fillna(df['Min_cargo_L'].min())
df['Front_headroom']=df['Front_headroom'].fillna(df['Front_headroom'].mean())
df['Front_legroom']=df['Front_legroom'].fillna(df['Front_legroom'].mean())
df['Rear_legroom']=df['Rear_legroom'].fillna(df['Rear_legroom'].mean())
df['Rear_shoulder']=df['Rear_shoulder'].fillna(df['Rear_shoulder'].mean())
df['Base_Power']=df['Base_Power'].fillna(df['Base_Power'].mean())
df['Fuel_capacity']=df['Fuel_capacity'].fillna(df['Fuel_capacity'].mean())
df['Towing'] = df['Towing'].fillna(7500.0)

In [7]:
df.head()

,Name,Base_price,Body_style,Seats,Base_Engine,Base_Power,Mileage,Drive,Towing,Min_cargo_L,Front_headroom,Front_legroom,Rear_legroom,Rear_shoulder,Fuel_capacity,Batt,Range
0,2021 Acura RDX,44505,SUV,5,Gasoline,272.0,9.9,AWD,1500.0,835.0,39.6,41.6,38.4,56.6,65.0,0.0,654.0
1,2022 Acura MDX,56405,SUV,7,Gasoline,290.0,11.2,AWD,5000.0,513.0,38.5,41.6,38.5,60.3,70.0,0.0,625.0
2,2021 Acura ILX,30805,Sedan,5,Gasoline,201.0,8.6,FWD,0.0,350.0,38.0,42.3,34.0,53.5,50.0,0.0,581.0
3,2022 Acura NSX,221500,Coupe,2,Hybrid,600.0,11.0,AWD,0.0,110.0,38.3,42.9,0.0,0.0,59.0,1.3,539.0
4,2021 Acura TLX,44105,Sedan,5,Gasoline,272.0,9.8,AWD,0.0,382.0,37.2,42.5,34.9,55.0,60.0,0.0,612.0

In [8]:
df = pd.get_dummies(df, columns=['Body_style', 'Base_Engine', 'Drive', 'Seats'])

In [9]:
df.head(10)

,Name,Base_price,Base_Power,Mileage,Towing,Min_cargo_L,Front_headroom,Front_legroom,Rear_legroom,Rear_shoulder,...,Drive_FWD,Drive_RWD,Seats_2,Seats_3,Seats_4,Seats_5,Seats_6,Seats_7,Seats_8,Seats_12
0,2021 Acura RDX,44505,272.0,9.9,1500.0,835.0,39.600000,41.600000,38.400000,56.600000,...,0,0,0,0,0,1,0,0,0,0
1,2022 Acura MDX,56405,290.0,11.2,5000.0,513.0,38.500000,41.600000,38.500000,60.300000,...,0,0,0,0,0,0,0,1,0,0
2,2021 Acura ILX,30805,201.0,8.6,0.0,350.0,38.000000,42.300000,34.000000,53.500000,...,1,0,0,0,0,1,0,0,0,0
3,2022 Acura NSX,221500,600.0,11.0,0.0,110.0,38.300000,42.900000,0.000000,0.000000,...,0,0,1,0,0,0,0,0,0,0
4,2021 Acura TLX,44105,272.0,9.8,0.0,382.0,37.200000,42.500000,34.900000,55.000000,...,0,0,0,0,0,1,0,0,0,0
5,2022 Alfa Romeo Giulia,55995,280.0,9.2,0.0,0.0,38.600000,42.400000,35.100000,53.600000,...,0,0,0,0,0,1,0,0,0,0
6,2022 Alfa Romeo Stelvio,57595,280.0,9.6,3000.0,525.0,40.200000,36.600000,31.900000,56.000000,...,0,0,0,0,0,1,0,0,0,0
7,2022 Aston Martin DB11,236500,527.0,11.6,0.0,0.0,39.897954,41.876053,32.761979,50.651385,...,0,1,0,0,1,0,0,0,0,0
8,2022 Aston Martin DBS,363800,715.0,13.8,0.0,0.0,39.897954,41.876053,32.761979,50.651385,...,0,1,0,0,1,0,0,0,0,0
9,2022 Aston Martin DBX,203500,542.0,15.2,6000.0,694.0,39.897954,41.876053,32.761979,50.651385,...,0,0,0,0,0,1,0,0,0,0

In [10]:
#df.to_csv('numeric_w_names.csv')

In [ ]:
from sklearn.preprocessing import StandardScaler
# Extract only some subset of columns to reduce computation time 
X = df[['mpg', 'disp', 'hp', 'wt']].values

# Standardize the features so that no feature dominates the
# distance computations due to unit scale
scaler = StandardScaler().fit(X)
X = scaler.transform(X)